
spring:
  application:
    name: transmart-proxy
  jackson:
    serialization:
      write_dates_as_timestamps: false
  mvc:
    favicon:
      enabled: false

server:
  port: 9050

keycloak:
  bearer-only: true
  use-resource-role-mappings: true
